version: "3"
services:
       movies-server:
           container_name: movies-server
           image: randraide/movies-server
           restart: always
           build: .
           ports:
             - "8080:8080"
           links:
             - mongo
           depends_on:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             volumes:
               - ./data:/data/db
             ports:
               - '27017:27017'